### ISSUE TITLE
Move parts.noisebridge.net to VPS

### ISSUE THREAD

**Issue by SuperQ** [noisebridge/infrastructure#131]
Let's move parts.noisebridge.net from pegasus to one of our VPS servers. `m4.noisebridge.net`.

**Comment by hzeller** [comment]
Ok, how do I get started ? I guess my ssh key needs to be somewhere, but is there a common way how we set up such system ? I suspect some ansible is involved somewhere ?

**Comment by SuperQ** [comment]
Yes, we'll have to add your key, and then create a `parts` role that deploys the system.

Can you list out the requirements for the parts software?

**Comment by hzeller** [comment]
FYI: code is on https://github.com/hzeller/stuff-org

Requirements
  - golang somewhat recent (after it supports http2). That means, younger than 2 years or so :)
  - the code has one external dependency (sqlite) which is important to go-get when building (ideally with the better dependency management thing that is now the way to go; deferring to @SuperQ to make that happen :)). But I guess you can also do some CircleCI magic to set that up ?
  - 500MiB for images (currently using about 100MiB), ideally more so that we can store hi-res versions of them.
  - go can run as http2 endpoint directly, but if there is some other reverse proxy there I am fine with that as well, as long as we can maintain http2-ness (it will allow fast parallel image delivery; right now we only to regular http1).

Then of course, we need to have a way to back this stuff up (database and images), but I suppose there is already something in place. Right now, the images are actually not being updated by the program yet (needed feature :) ), so they are anywhere somewhere external already ( https://goo.gl/photos/KVbiN8rGYwTXAjH49 ), so mostly interesting is the database. Which could be a simple git push to somewhere.

**Comment by SuperQ** [comment]
Yea, we can do the same CircleCI magic on the `stuff-org` repo. Adding build-time dependencies is pretty easy.

Caddy server should be able to handle the http2 stuff, as well as deal with letsencrypt.

For backups, I'm thinking about using [Restic](https://restic.net/)

**Comment by hzeller** [comment]
What are the next steps @SuperQ , now that we have CircleCI set up and stuff ?

**Comment by SuperQ** [comment]
We need a release publishing API key named `GITHUB_TOKEN` in the circleci environment. If you can follow the instructions on https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/.

The token needs `repo` and `admin:repo_hook` permissions.

Once you have the key string, add the env variable to https://circleci.com/gh/hzeller/stuff-org/edit#env-vars.

**Comment by SuperQ** [comment]
This is done.
