### ISSUE TITLE
Migrate donate.noisebridge.net off of ratchet

### ISSUE THREAD

**Issue by ruthgrace** [noisebridge/infrastructure#195]
To do:
* back up what's on rachet
* test and deploy ansible code for deploying donate.noisebridge.net
* deploy with test API keys to validate
* deploy with real API keys

**Comment by marcidy** [comment]
See #196 for what was done post the meeting

Since no one really knows ruby/rails, there's strong incentive to test the python version.  

I created a repo python-donate-nb so we can deploy that from noisebridge's repo, but will proceed with the existing architecture first.  The python package is nearly ready to alpha test.

Next I will write an ansible playbook for deploying (either) donate on m5 and SuperQ will familiarize themself with the existing code and deploying rails, and taking a backup of the data on ratchet.

**Comment by SuperQ** [comment]
I've backed up the existing deploy on ratchet, as well as the current database data.

**Comment by marcidy** [comment]
@rizend and I discussed this last night.  It's my opinion that deploying python-donate, since it's in a language we are comfortable in, might be significantly easier.  There are still things which need to be done.  

1) I need to finish covering the routes with test cases
2) we need to build the role (@rizend is working on this)

It seems like focussing on one deployment will get it done faster.

Right now, python-donate can perform the basic functionality required to take donations.  I have tested it with stripe test keys and the data shows up in the stripe database.   the balance of the functionality is noisebridge specific, things like handling projects and the new functions I have introduced to help finances.  These are not critical for initial deployment.

There are two other issues.
3) the database for ruby-donate contains information about projects and also data from all past requests.  We have it backed up, and can migrate it to the new database with a migration script, but this is not started.  
4) The part about saving all the new requests can be handled via logging, which is already configured in python-donate.  We would backload all the data post going live with the new site.

The idea is that focussing on the implementation with the developer still here will be easier to debug and deal with rather than trying to read through code in a language that we do not have expertise.

let me know what you think, @rizend let me know if I mischaractized you or left anything out.

**Comment by SuperQ** [comment]
What about writing it in Rust? :trollface:

**Comment by marcidy** [comment]
Hey all.  test-donate.noisebridge.net is up!  it's using test keys to actually hit stripe with good data.  You can use testing cards from stripes website:
https://stripe.com/docs/testing

i have done limited testing.  There's a lot of unittests with good coverage, but i have not cycled through all possible input orderings nor tried to trigger multiple problems.  Please have at it.

@SuperQ I added a reverse proxy to the existing caddy file. Was I supposed to do that? appears to work.

note that the server is out of debug mode, but logging is on full blast.

it's running in /home/rando/donate right now.  no reason.  Probably should pick a good place.

pls test thx

**Comment by SuperQ** [comment]
We should get this deployed with Ansible.

The Caddyfile for m5 is [group_vars/m5-noisebridge-net/caddy.yml](https://github.com/noisebridge/infrastructure/blob/master/group_vars/m5-noisebridge-net/caddy.yml).

For deploying the code, we could either deploy a systemd unit and put the code in /srv/donate, or we could use Docker and fetch it with Ansible.

**Comment by rizend** [comment]
I'm currently working on a role that does the the systemd unit and code in `/srv/pydonate` approach;

**Comment by marcidy** [comment]
> We should get this deployed with Ansible.
> The Caddyfile for m5 is [group_vars/m5-noisebridge-net/caddy.yml](https://github.com/noisebridge/infrastructure/blob/master/group_vars/m5-noisebridge-net/caddy.yml).

#198

**Comment by ruthgrace** [comment]
Ran `ansible-playbook site.yml --limit noisebridge-net` to deploy the Paypal link to the donate page that R set up (cc @rizend @marcidy)

I don't see the PayPal link, it just says "Donate is down for maintenance". HTTPS works now, though

**Comment by ruthgrace** [comment]
Hmm, I'm getting

```fatal: [m5.noisebridge.net]: UNREACHABLE! => {"changed": false, "msg": "SSH Error: data could not be sent to remote host \"m5.noisebridge.net\". Make sure this host can be reached over ssh", "unreachable": true}```

But I can indeed SSH to m5.noisebridge.net ...

**Comment by ruthgrace** [comment]
the full output with error:

```ruthmacbook12:infrastructure ruthgracewong$ ansible-playbook site.yml --limit donate-noisebridge-net

PLAY [node defaults] ***********************************************************

TASK [Gathering Facts] *********************************************************
ok: [m5.noisebridge.net]

TASK [utils : Install packages] ************************************************
ok: [m5.noisebridge.net]

TASK [utils : Setup sudoers] ***************************************************
ok: [m5.noisebridge.net]

TASK [security : Add user] *****************************************************
ok: [m5.noisebridge.net] => (item=rando)
ok: [m5.noisebridge.net] => (item=ruthgrace)
ok: [m5.noisebridge.net] => (item=superq)

TASK [security : Grant sudo] ***************************************************
ok: [m5.noisebridge.net] => (item=rando)
ok: [m5.noisebridge.net] => (item=ruthgrace)
ok: [m5.noisebridge.net] => (item=superq)

TASK [security : github SSH key] ***********************************************
ok: [m5.noisebridge.net] => (item=rando)
ok: [m5.noisebridge.net] => (item=ruthgrace)
ok: [m5.noisebridge.net] => (item=superq)

TASK [security : static SSH key] ***********************************************
skipping: [m5.noisebridge.net] => (item=rando)
skipping: [m5.noisebridge.net] => (item=ruthgrace)
skipping: [m5.noisebridge.net] => (item=superq)

TASK [security : Disallow password authentication] *****************************
ok: [m5.noisebridge.net]

PLAY [noisebridge-net] *********************************************************
skipping: no hosts matched

PLAY [donate-noisebridge-net] **************************************************

TASK [Gathering Facts] *********************************************************
fatal: [m5.noisebridge.net]: UNREACHABLE! => {"changed": false, "msg": "SSH Error: data could not be sent to remote host \"m5.noisebridge.net\". Make sure this host can be reached over ssh", "unreachable": true}
	to retry, use: --limit @/Users/ruthgracewong/infrastructure/site.retry

PLAY RECAP *********************************************************************
m5.noisebridge.net         : ok=7    changed=0    unreachable=1    failed=0
```

**Comment by ruthgrace** [comment]
aha, i was able to deploy by making this change: https://github.com/noisebridge/infrastructure/pull/206
FYI @marcidy @rizend

**Comment by marcidy** [comment]
@SuperQ where would the appropriate place for database config be for the flask server?
1. hard coded in the donate package settings files
2. a config file (yaml, ini, whatever) in the package directory or elsewhere managed by ansible
3. env vars managed by ansible

I'm thinking in a scenario where we change databases either in fail-over, back-up, to test or something like that.

**Comment by SuperQ** [comment]
Probably 2 or 3. I prefer config files.

Take a look at the library-org PR I posted. All of the secrets are in a template config file and loaded by flask.

**Comment by marcidy** [comment]
the mysql connector for python requires mysql-config which is part of the debian package libmysqlclient-dev.   I assume this goes in ansible somewhere?

**Comment by SuperQ** [comment]
Yes, I installed `libperconaserverclient21-dev` which provides `mysql_config`. We can add that to the Ansible package requirements.

**Comment by marcidy** [comment]
ok I posted #212 for another addition, but it's the last lib, donate install works after that.  Another question.  I need to add a user with privs to the database.  Do I use this?
https://docs.ansible.com/ansible/latest/modules/mysql_user_module.html

**Comment by marcidy** [comment]
@rizend @SuperQ What do we need to get this up ASAP?  

At a minimum I need something to monitor it and notify if it's down, possibly try to restart it 3 times or something.  I think using a ".env" file is fine for right now and is not a security risk.  

I dont need everything in ansible to go live, we can finish that over the course of the next two weeks and I'll keep it up as I can manually.

**Comment by rizend** [comment]
To deploy this through ansible:
- #199 needs to be reviewed
- if it hasn't been done yet, the database needs to be setupybook for m5
- the pydonate role needs to be added to a playbook
  - the relevant secrets need to be put in a m5 specific encrypted file (probably with ansible-vault)
- All relevant roles need to be deployed to m5

**Comment by marcidy** [comment]
Added one comment one #199 about the "none"s about what their expliclt
purpose is, looks good otherwise.

what do you mean by setupybook?  I set up the production database, it's
initialized as well, the user is there and has privileges and right
password (though i need to have the vault password to really check it's
inline, or maybe that goes in ansible as well?).  Should be ready to go.

**Comment by rizend** [comment]
setupybook was a typo

**Comment by marcidy** [comment]
hat was it supposed to be?  Just setup?

**Comment by rizend** [comment]
Just setup; I edited the post so it's fixed now.

**Comment by marcidy** [comment]
Thanks!  so that's finished.  I need to read it to see if I understand where things will be deployed et so I can check the deploy went well, but it looks good.  just want SuperQ to review since it's ansible stuff and this will be production.

**Comment by marcidy** [comment]
I'm running a test deployment now!  will be debugging today and hopefully we can deploy to production this week.

**Comment by marcidy** [comment]
I'm deploying off @rizend's branch which i know is not finished, but it doesn't seem to enforce that the user's home directory (/srv/donate) has to be in the created group.  In this case the directory already existed, created Oct 7 2018, in /srv/donate.  The repo was never downloaded but I'm not sure if that's why.  I'm unclear where the deployment logs go.

**Comment by SuperQ** [comment]
I made a quick dashboard for the basic python metrics: https://grafana.noisebridge.net/d/JQxoHFSZz/donate

**Comment by marcidy** [comment]
I'm stuck because of this:
 
TASK [pydonate : Checkout repository] ***************************************************************************
fatal: [m5.noisebridge.net]: FAILED! => {"before": "211deca826f3e6297f7ba9ff38d7835d4300aec3", "changed": false, "msg": "Local modifications exist in repository (force=no)."}

probably because i pushed a change to the repo. I reverted the change, but I'm guessing i need to find and fix where-ever this is.

/srv/pydonate/code/scripts/initialize_database.py depends on the environment variables in the ./srv/pydonate/code/.env file.

I dont want to have to update 2 different repos to change env vars. I would like all the env var config moved to ansible, and I will deal with missing envvars in the donate code.

What is the best way to achieve this?  

You can see the file on m5:
/srv/pydonate/code/.env

I would like to define env vars in only one place and be able to use them for various tasks as desired.

**Comment by SuperQ** [comment]
You're going to have to have ENV vars in two places. One to define what the sensible defaults are, it should be something like `env-example`. Then the production one should read from `.env`.

It looks like you have a local edit:
```
root@m5:/srv/pydonate/code# git diff
diff --git a/scripts/initialize_database.py b/scripts/initialize_database.py
index 1ce0537..0cc9a24 100644
--- a/scripts/initialize_database.py
+++ b/scripts/initialize_database.py
@@ -24,6 +24,7 @@ def create_session():
     else:
         raise Exception("FLASK_ENV not recognized")
 
+    print(config.SQLALCHEMY_DATABASE_URI)
     engine = create_engine(config.SQLALCHEMY_DATABASE_URI)
     Session = sessionmaker(bind=engine)
     session = Session()
```

**Comment by marcidy** [comment]
Oh i thought it would overwrite that.  Thanks!

**Comment by rizend** [comment]
@marcidy you can add `force: yes` to the invocation of the [ansible git module](https://docs.ansible.com/ansible/latest/modules/git_module.html) in the [`Checkout repository`](https://github.com/noisebridge/infrastructure/blob/master/roles/pydonate/tasks/main.yml#L43) task if you want it to overwrite local changes.

**Comment by marcidy** [comment]
while testing the production deployment role, i found an issue where the donate app is not filling out a field in the stripe API correctly, such that the transaction occurs, but the email address of the donor isn't reporting in the correct field in the stripe dashboard.  This doesn't seem to be an issue in test stripe env.  bug hunting is ensuing.

**Comment by marcidy** [comment]
nope, im wrong, i had looked at the wrong log data in stripe.  it was a real issue throughout testing.  fixing ensues.

**Comment by marcidy** [comment]
see: https://github.com/noisebridge/python-nb-donate/issues/31

For clarity, there isn't something wrong, as much as it's not _exactly_ how old donate works.  old donate creates customers on every charge which is not necessary, but my preference is always replicate first when possible.

**Comment by marcidy** [comment]
I really need to stop hitting the close button.

**Comment by marcidy** [comment]
#223 completes migration

**Comment by marcidy** [comment]
I'm going to put this in BAU and all further work will be considered enhancements to donate.  thanks everyone!
